name: Deploy Easily GTM

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ~/.npm
          node_modules/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: npm i
      
    - name: Build library
      run: node_modules/.bin/ng build --project=easily-gtm --prod

    - name: Move LICENSE
      run: cp -r LICENSE dist/easily-gtm

    - name: Deploy
      run: cd dist/easily-gtm/ && npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    - name: Read package.json
      uses: tyankatsu0105/read-package-version-actions@v1
      with: 
        path: "projects/easily-gtm/"
      id: package-version

    - name: Send message Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Easily GTM was deployed on npmjs by {{ repo.namespace }}
          New version is ${{ steps.package-version.outputs.version }}